version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo


    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package-lock.json" }}
          - v2-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - "$HOME/.npm"
          key: v2-dependencies-{{ checksum "package-lock.json" }}

      - run: npm run -s typecheck

      - run: npm run -s lint

nnpm install (with no args, in package dir) npm install [<@scope>/]<name> npm install [<@scope>/]<name>@<tag> npm install [<@scope>/]<name>@<version> npm install [<@scope>/]<name>@<version range> npm install <alias>@npm:<name> npm install <git-host>:<git-user>/<repo-name> npm install <git repo url> npm install <tarball file> npm install <tarball url> npm install <folder> aliases: npm i, npm add common options: [-P|--save-prod|-D|--save-dev|-O|--save-optional] [-E|--save-exact] [-B|--save-bundle] [--no-save] [--dry-run]
